### ISSUE TITLE
Support for Kärnten Netz

### ISSUE THREAD

**Issue by MaGermadnik** [awattar-backtesting/awattar-backtesting.github.io#1]
Hi, great Idea!
can you please add support for https://kaerntennetz.at/. See my example, attached.
[KNetzBeispiel.csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/11185899/KNetzBeispiel.csv)

thank you!

**Comment by lewurm** [comment]
Thank @MaGermadnik.  I've added support for Kärnten Netz, please confirm if it works.

Additionally it would be great if you could provide steps how to obtain this file (and if not that clear, maybe include screenshots 🙂 ). Something similar to what I've added for NetzNÖ already.

**Comment by MaGermadnik** [comment]
@lewurm thanks! the step by step tutorial below.

1) Gehe auf https://kaerntennetz.at/
2) Kundenportal
3) Einloggen
4) "Profildownload" unter "meine.messwerte" auswählen
5) Richtigen Zähler auswählen. Achtung, nicht den Einspeisepunkt wählen.
6) Download (es kann kein Zeitraum ausgewählt werden)

![KNetzProfildownload](https://user-images.githubusercontent.com/60483118/230840510-54df7c91-7e82-4cd1-94a4-0e887c8d6c73.png)

**Comment by MaGermadnik** [comment]
@lewurm Unfortunately, at Kärnten Netz, the timeframe cannot be selected. The data of the last 3 years is always downloaded. The file size is approximately 5MB. When I try this, I see the following error in the browser console and cant see any chart.

![KNetzBigFileUpload](https://user-images.githubusercontent.com/60483118/230841323-51708988-a43f-47eb-a24a-bd75070db2d2.png)

It would be great to select a specific month (or year) or maybe the simplest solution, you are processing only the last X days in the file? (note: the newest entries are at the end of the file)

**Comment by lewurm** [comment]
uhh, good catch @MaGermadnik.  I pushed a fix that avoids using varargs, and instead iterates over the byte buffer. Could you try again?

**Comment by MaGermadnik** [comment]
@lewurm Great, it is working now :) I found another small bug, but it is not related to KNetz, so I will open a new issue. 
Thanks, this is realy helpful for me :)
