### ISSUE TITLE
Neuer Netzbetreiber Salzburg AG

### ISSUE THREAD

**Issue by mkastinger** [awattar-backtesting/awattar-backtesting.github.io#10]
Hallo,

anbei eine CSV von Salzburg AG, wäre super, wenn du das unterstützen könntest.

lg
[Lastprofilwerte.csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/11999285/Lastprofilwerte.csv)

**Comment by lewurm** [comment]
Hallo @mkastinger , sorry ich habe dieses issue übersehen. Sollte jetzt funktionieren, bitte wieder öffnen falls nicht.
