### ISSUE TITLE
Netz Burgenland

### ISSUE THREAD

**Issue by karaokejohnson** [awattar-backtesting/awattar-backtesting.github.io#12]
Guten Morgen,

gibt es die Möglichkeit dieses Tool mit CSV Dateien von Netz Burgenland zu nutzen? 
Ich habe als Anlage ein Lastprofil angehängt.

LG
Christoph 

PS: bin durch einen Bekannten auf dieses Tool aufmerksam gemacht worden und finde es echt toll!!

[Netz Burgenland.csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/12247456/Netz.Burgenland.csv)

**Comment by lewurm** [comment]
Danke @karaokejohnson 🙂 Sollte jetzt funktionieren, bitte testen.

**Comment by karaokejohnson** [comment]
Danke @lewurm, es hat geklappt und funktioniert, soweit ich das als Laie beurteilen kann!
