### ISSUE TITLE
add https://www.spottyenergie.at/

### ISSUE THREAD

**Issue by lewurm** [awattar-backtesting/awattar-backtesting.github.io#14]
to be done

**Comment by GerhardGoeschl** [comment]
> to be done

Ist das nicht ohnedies schon implementiert?

**Comment by GerhardGoeschl** [comment]
Spotty Direkt - alt (-02/24) könnte man noch dazunehmen:
Stündlicher Börsenpreis von EPEX Spot Day Ahead Markt + Service Fee 1.788 Cent /kWh brutto
Grundgebühr 2.40 Euro im Monat brutto

**Comment by lewurm** [comment]
Fixed by #34

**Comment by lewurm** [comment]
> Spotty Direkt - alt (-02/24) könnte man noch dazunehmen: Stündlicher Börsenpreis von EPEX Spot Day Ahead Markt + Service Fee 1.788 Cent /kWh brutto Grundgebühr 2.40 Euro im Monat brutto

Eigentlich möchte die Altverträge eh rausnehmen um es etwas übersichtlicher zu machen, werd ich demnächst mal in Angriff nehmen.

**Comment by GerhardGoeschl** [comment]
> > Spotty Direkt - alt (-02/24) könnte man noch dazunehmen: Stündlicher Börsenpreis von EPEX Spot Day Ahead Markt + Service Fee 1.788 Cent /kWh brutto Grundgebühr 2.40 Euro im Monat brutto
> 
> Eigentlich möchte die Altverträge eh rausnehmen um es etwas übersichtlicher zu machen, werd ich demnächst mal in Angriff nehmen.

Bitte nur optional. Ich z.B. habe noch einen alten Spotty Direkt Vertrag wo die 0,36 Aufschlag für die Zertifikate (noch) nicht anfallen. Könnte mir vorstellen, dass es da auch noch ein paar andere außer mir gibt. ;-)

**Comment by lewurm** [comment]
nagut 🙂 

einen Weg um Tariffe zu filtern bzw. selber einen Tarif hinzfügen wäre super.  Wenn ich nur besser in diesem Front-End zeugs wäre 😉
