### ISSUE TITLE
add Netz Burgenland

### ISSUE THREAD

**Issue by karaokejohnson** [awattar-backtesting/awattar-backtesting.github.io#17]
Hallo,
Netz Burgenland hat das Format seiner CSV Datei etwas geändert, wäre es möglich dies zu adaptieren?

Herzlichen Dank schon jetzt!

Liebe Grüße
Christoph 

[AT0090000000000000000000000049656-01082023-31082023 (1).csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/12489299/AT0090000000000000000000000049656-01082023-31082023.1.csv)

**Comment by lewurm** [comment]
Danke! Sollte jetzt funktionieren

**Comment by karaokejohnson** [comment]
Danke, klappt jetzt wieder!
LG
