### ISSUE TITLE
Netz Burgenland

### ISSUE THREAD

**Issue by karaokejohnson** [awattar-backtesting/awattar-backtesting.github.io#18]
Hallo,
leider funktioniert bei mir Netz Burgenland aus irgendeinem Grund nicht mehr, könntest du da eventuell einen Blick darauf werfen - Danke!

LG
Christoph 
[AT0090000000000000000000000049656-01102023-31102023.csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/13236556/AT0090000000000000000000000049656-01102023-31102023.csv)

**Comment by lewurm** [comment]
Gibt's ja gar ned, jetzt hams das Format schon wieder geändert 😅  Danke für den Report, sollte jetzt funktionieren.

**Comment by karaokejohnson** [comment]
Danke fürs rasche ändern! Jetzt funktioniert es wieder, dafür haben sie die letzten 10 Jahre davor nichts geändert! ;-) LG
