### ISSUE TITLE
Falscher Verechnungsfaktor beim neuen Awattar Tarif

### ISSUE THREAD

**Issue by lefduti** [awattar-backtesting/awattar-backtesting.github.io#19]
https://github.com/awattar-backtesting/awattar-backtesting.github.io/blob/c0f762f8c5efd7f12b81ee09f620b4fde670fb98/docs/app.js#L121C1-L121C1

Awattar verrechnet 1.5ct/kWh und nicht 1.8 wie im Code angegeben.

https://www.awattar.at/tariffs/hourly

**Comment by lewurm** [comment]
Im Tarifblatt von aWATTar ist der Markup ohne 20% USt. angegeben.  Die 1,8ct/kWh sind inklusive 20% USt.  Oder hab ich etwas übersehen?

**Comment by lefduti** [comment]
Okay das stimmt. So weit hab ich dann nicht gedacht als ich den Kommentar geschrieben hab 😅
