### ISSUE TITLE
Uploading the same file, multiple times

### ISSUE THREAD

**Issue by MaGermadnik** [awattar-backtesting/awattar-backtesting.github.io#2]
Uploading the same file a second time, didn't recognise, that there are the same data included and it is summed up and duplicated in "Übersicht Energiekosten"
In this example I did the upload three times. First line 19,62kWh, second line 39,25 (=19,62+19,62), third line 58,87 (=19,62+19,62+19,62)

![DuplicateUploads](https://user-images.githubusercontent.com/60483118/230847679-d8d68098-7764-4ac7-af23-6ef170ed7fc0.png)

Each upload should clear the previous result?

**Comment by lewurm** [comment]
Good point, thank you 👍   Please test, and feel free to reopen if it doesn't meet your expectations.
