### ISSUE TITLE
feature request: durchschnitts (epex) strompreis pro monat und tag anzeigen

### ISSUE THREAD

**Issue by tkaiser** [awattar-backtesting/awattar-backtesting.github.io#20]
Ich fänd es cool, wenn man in der tabelle in der monatszeile, optional auch bei dem tag, eine zusätzliche spalte mit dem durchschnitts-börsenpreis für den jeweiligen zeitraum hätte. so könnte man sehen, wieviel man selber drunter bzw (hoffentlich nicht) drüber ist.

ich denke das sollte eine relativ low hanging fruit sein

würde die spalte "Durchschnitt" eventuell in "Erzielter Preis" umbennen und die neue Spalte halt "Börsenpreis Durchschnitt" oder o.

hier rein die neue
![image](https://github.com/awattar-backtesting/awattar-backtesting.github.io/assets/8970774/e5013c77-f519-4459-8446-bd11167c54db)

**Comment by tkaiser** [comment]
ich war so frei: https://github.com/awattar-backtesting/awattar-backtesting.github.io/pull/21

**Comment by tkaiser** [comment]
hab jetzt nochmal ein bisschen drüber nachgedacht und bin mir gar nicht so sicher ob die info recht sinnvoll ist. man hat halt einen vergleich wie es gewesen wäre, wenn man komplett konstanten stromverbrauch gehabt hätte, aber das ist ja eh komplett unrealistisch. ein "normaler", unangepasster stromverbrauch, wo man viel zu den teuren morgen- und abendzeiten verbraucht, würde wohl weit über dem durchschnitt reinkommen. ich hab jetzt ein paar monate von mir als stichprobe genommen, ich bin meistens knapp unter oder über dem schnitt. bin mir aber nicht sicher wie wertvoll diese erkenntnis ist ;) 

naja hilfts nix so schadets nix, und es waren nur 15 min aufwand also kannst auch ruhig ablehnen.

**Comment by lewurm** [comment]
Ich werds mal rein nehmen, aber du hast recht, tatsächlich wären Vergleiche mit [Standardlastprofile](https://de.wikipedia.org/wiki/Standardlastprofil#Standardlastprofile_(Strom)_des_BDEW) interessanter, z.B. H0.  Mal schauen ob ich dafür eine gute Definition auftreiben und einarbeiten kann.

**Comment by tkaiser** [comment]
aah ja die gibts ja auch noch, das wär eine coole idee tbh. hört sich auch relativ easy machbar an

**Comment by lewurm** [comment]
Das sieht brauchbar aus: https://www.bdew.de/media/documents/Profile.zip

**Comment by tkaiser** [comment]
ich hab dir ein google doc geshared, da hab ich versucht das h0 mal in ein vernünftiges format zu bringen. aber mal nur 1 der 6 kategorien (wochentag/WE, sommer/winter/übergang), für mehr reichts heute nicht mehr. der rest sollt nur mehr copy/paste sein

**Comment by lewurm** [comment]
H0 Lastprofil Durchschnitt wurde hinzugefügt: https://github.com/awattar-backtesting/awattar-backtesting.github.io/pull/23
