### ISSUE TITLE
Netto/Brutto Vermischungsfehler

### ISSUE THREAD

**Issue by cgschnell72** [awattar-backtesting/awattar-backtesting.github.io#29]
Der aktuelle Darstellungsstatus mit vermischten Netto/Brutto-Beträgen birgt das Risiko von Fehlern, die wohl auch begangen wurden.

Zumindest für die Spalte (smartCONTROL ab 2023/10) ist die Mwst für den variablen Preis enthalten, NICHT aber für den Aufschlag von 1,44 ct/kWh wie auch für die 2,99 EUR Grundgebühr pro Monat!

Änderungswunsch: Entweder (a) reine Nettoberechnung oder (b) #24.

**Comment by lewurm** [comment]
Hallo @cgschnell72,

Danke für deinen Post.

![Screenshot 2024-01-08 at 23 24 45](https://github.com/awattar-backtesting/awattar-backtesting.github.io/assets/75403/01bd293e-f56b-4c88-82cb-b871e77deac7)

die 1,44 ct/kWh bzw. 2,99 EUR Grundgebühr sind schon inklusive Umsatzsteuer. Wo siehst du da die Vermischung?

**Comment by cgschnell72** [comment]
Richtig, die Vermischung war nur in meinem Kopf 😉. Ich wollte nicht wahrhaben, dass Unternehmen hier die Aufschläge schon inklusive Steuer angeben, auch wenn explizit "inkl. 20 % USt." angeführt ist.
