### ISSUE TITLE
Netzbetreiber Ebner Strom

### ISSUE THREAD

**Issue by FlorianW208** [awattar-backtesting/awattar-backtesting.github.io#3]
Hallo, anbei eine CSV des Netzbetreibers Ebner Storm

weiters wäre es sinnvoll die CSV-Dateien zu beschreiben, so kann jeder seine eigene CSV-Datei herrichten.

Format von Ebner Strom:
- Zeitstempel in String (d.m.Y H:i)
- Zählerart
- kw
- Zeitraum

[Lastprofil.xlsx](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/11188522/Lastprofil.xlsx)

![image](https://user-images.githubusercontent.com/68705032/230849200-e9b1b09c-9beb-4ffe-9268-a5e71411eed5.png)

**Comment by lewurm** [comment]
Danke @FlorianW208  🙂  Ich habe soeben Support für Ebner Strom gepusht, bitte testen.

Könntest Du noch Schritte posten (eventuell mit Screenshot) wie man zu dieser Datei kommt? Siehe Beispiele von den anderen Netzbetreibern auf der Seite.

> weiters wäre es sinnvoll die CSV-Dateien zu beschreiben, so kann jeder seine eigene CSV-Datei herrichten.

Hmm, einfach etwas nachmachen was eines der Netzbetreiber macht? Siehe für Samples: https://github.com/awattar-backtesting/awattar-backtesting.github.io/tree/main/samples

Oder meinst du etwas anderes?
