### ISSUE TITLE
Netzbetreiber Wiener Netze

### ISSUE THREAD

**Issue by horakg** [awattar-backtesting/awattar-backtesting.github.io#4]
would be great if you can add Wiener Netze as "Netzbetreiber"

[intervalle-20230410-102521.csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/11188950/intervalle-20230410-102521.csv)

How to download it:
1. Login to https://smartmeter-web.wienernetze.at
2. Go to  "Datenexport"
3. Choose the correct timeframe
4. Select Viertelstundewerte
5. Select only one "Zählpunktnummer" if you have multiple ones
6. Click exportieren

**Comment by lewurm** [comment]
Thank you @horakg.  It should work now, please verify 🙂

**Comment by horakg** [comment]
thx @lewurm. It's working
