### ISSUE TITLE
Energienetze Steiermark

### ISSUE THREAD

**Issue by HeliStmk** [awattar-backtesting/awattar-backtesting.github.io#43]
hallo!

hätte da einen beispielexport (viertelstündlich) von Energienetze Steiermark:
[export_AT0000000000000000000000000000000_Statistikzeitraum_29.04.2024.csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/15148346/export_AT0000000000000000000000000000000_Statistikzeitraum_29.04.2024.csv)

danke!

**Comment by lewurm** [comment]
Danke @HeliStmk!  Sollte jetzt wieder funktionieren 🙂
