### ISSUE TITLE
Netzbetreiber eww (Wels)

### ISSUE THREAD

**Issue by rathi66** [awattar-backtesting/awattar-backtesting.github.io#45]
Anbei der Export vom eww in Wels
[Verbrauch (1).xlsx](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/15303112/Verbrauch.1.xlsx)

**Comment by lewurm** [comment]
Hallo @rathi66 ! Vielen Dank für den Export.  Sollte nun auch für eww Wels funktionieren, bitte testen 🙂

**Comment by rathi66** [comment]
Hallo @lewurm , vielen Dank funktioniert. Seit ein paar Tagen hat eww das Format erneut angepasst, anbei ein neuer export.
[Verbrauch.xlsx](https://github.com/user-attachments/files/15969472/Verbrauch.xlsx)

**Comment by lewurm** [comment]
Danke @rathi66, sollte nun für das neue Format funktionieren

**Comment by rathi66** [comment]
Danke @lewurm, funktioniert perfekt!
