### ISSUE TITLE
Energie Netze Steiermark

### ISSUE THREAD

**Issue by emjayhome** [awattar-backtesting/awattar-backtesting.github.io#48]
Hallo,

im Anhang der Export der Energie Netze Steiermark (https://www.e-netze.at). Wäre es möglich diese Daten zu importieren?

Danke!

LG EmJay
[VerbrauchsdatenENetze2024.xlsx](https://github.com/user-attachments/files/15743116/VerbrauchsdatenENetze2024.xlsx)

**Comment by lewurm** [comment]
Danke!

Anscheinend haben die Energie Netze Steiermark schon wieder (!) ihr Format geändert.  Hum 😕 

Sollte jetzt funktionieren, bitte testen.
