### ISSUE TITLE
LinzAG Upload is not working because of wrong headlines

### ISSUE THREAD

**Issue by Hiesx** [awattar-backtesting/awattar-backtesting.github.io#51]
The new default headlines are;
Datum von;Datum bis;Verbrauch in kWh;Ersatzwert

So the sample LinzAG.csv file needs to be changed. 
![grafik](https://github.com/awattar-backtesting/awattar-backtesting.github.io/assets/56231126/50307afa-648c-48a9-9b37-0748d075ba5d)

**Comment by lewurm** [comment]
Thanks for the report @Hiesx!  Alas Netzprovider constantely change their format, so we just have to deal with it 🙁  We usually add a new variant, so it would be great if you could share an example export with the new format.

**Comment by Hiesx** [comment]
Thanks for the quick reply :)
I've already seen it in the issues, it would be really great if everything was standardized, but apparently you can't demand that in Austria :D 
Here is an example export for LinzAG
[LinzAG-v2.CSV](https://github.com/user-attachments/files/16172687/LinzAG-v2.CSV)

**Comment by lewurm** [comment]
I guess we must be grateful that Netzbetreiber are required to offer a CSV export 😄 

Thanks for sharing your export, it should work now.
