### ISSUE TITLE
awattar fügt 3% zum absoluten betrag des börsenpreises hinzu

### ISSUE THREAD

**Issue by kl-gh** [awattar-backtesting/awattar-backtesting.github.io#52]
Bei der Formel des Energieverbrauchspreises von Awattar sieht es so aus als würden die 3% negative Preise noch weiter sinken lassen. Bei negativen Preisen verwenden Sie allerdings den absolut Wert.

Beispiele:
10 Cent: 
10  + ( 10 * 0,03) = 10,3 Cent

-10 Cent: 
-10 + (10 * 0,03) = -9,7 Cent

Quelle: aWATTar-Tarifblatt-HOURLY-v2.pdf

> **Preisanpassungsmethode**
> Der Preis basiert auf den 24 Stundenpreisen von der Strombörse EPEX Spot ®, die in der Day-Ahead-Auktion für
> die Österreich betreffende Preiszone ermittelt werden. Er enthält ebenfalls eine Ausgleichsenergiekomponente von
> 3% auf den Börsenpreis (diese fällt auf den Betrag des Börsenpreises an, d.h. **bei negativen Preisen wird trotzdem
> ein positiver Wert von 3% verrechnet**) ...

**Comment by lewurm** [comment]
Ein Beispiel aus der Praxis 🙂 
https://www.energiesparhaus.at/forum-hat-sich-schon-wer-mit-awattar-befasst/65016_65#753732
