### ISSUE TITLE
Wiener Netze Datenupload 

### ISSUE THREAD

**Issue by QGgWW2WhH** [awattar-backtesting/awattar-backtesting.github.io#56]
[TAGESWERTE-20211114-bis-20241113.csv](https://github.com/user-attachments/files/17731539/TAGESWERTE-20211114-bis-20241113.csv)
Fehlermeldung in Konsole

**Comment by lewurm** [comment]
Hallo! Das ist ein tagesweiser Export, das Tool benötigt 15min Werte. Siehe Beschreibung auf der Webseite:

<img width="539" alt="Screenshot 2024-11-13 at 21 40 39" src="https://github.com/user-attachments/assets/4bdd0a05-22e3-461a-8d65-edfaf43db36f">
