### ISSUE TITLE
Netzbetreiber Stromnetz Graz

### ISSUE THREAD

**Issue by j0hann3sk** [awattar-backtesting/awattar-backtesting.github.io#7]
Hey!
Support für Stromnetz Graz wäre toll.
Hier das File aus dem Web-Portal:
[stromnetz graz.csv](https://github.com/awattar-backtesting/awattar-backtesting.github.io/files/11260698/stromnetz.graz.csv)
Danke!

**Comment by lewurm** [comment]
Danke, sollte jetzt funktionieren 🙂
